# Generated by Django 4.2.6 on 2024-04-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='newdoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.TextField()),
                ('Password1', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='brainscans',
            name='imageName',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
