# Generated by Django 4.2.6 on 2024-04-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newdoctor',
        ),
    ]
