# Generated by Django 4.2.6 on 2024-04-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_delete_newdoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.TextField()),
                ('Password1', models.TextField()),
            ],
        ),
    ]
