# Generated by Django 4.2.6 on 2024-04-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_newdoctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
