# Generated by Django 4.2.6 on 2024-05-05 17:06

import cv.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brainscans',
            name='imageName',
        ),
        migrations.AddField(
            model_name='brainscans',
            name='doctor',
            field=models.ForeignKey(default=cv.models.BrainScans.get_default_doctor_id, on_delete=django.db.models.deletion.CASCADE, related_name='brain_scans', to='cv.newdoctor'),
        ),
        migrations.AlterField(
            model_name='brainscans',
            name='prediction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
