# Generated by Django 4.2.6 on 2024-05-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_remove_brainscans_imagename_brainscans_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainscans',
            name='imageName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
