# Generated by Django 4.2.6 on 2024-05-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_brainscans_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdoctor',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
